import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { 
  Container,
  GeneralContainer
} from '../styles/home/homePageStyles'
import { parseCookies } from 'nookies'
import DesktopNavbar from '../components/navbars/desktopNavbar'
import Canva from '../components/canva/canva'

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Drawing app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300&family=Noto+Sans&family=Roboto&family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet" />
      </Head>
      {/* <DesktopNavbar />
      <GeneralContainer></GeneralContainer> */}
      <Canva width={500} height={300} />
    </Container>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { 'drawingauth.token': token } = parseCookies(ctx)

  if (!token) {
    return {
      redirect: {
        destination: "/login",
        permanent: false
      }
    }
  }

  return {
    props: {}
  }
}

export default Home
