import { useState } from "react"
import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { 
  Container,
  GeneralContainer,
  ActionsContainer,
} from '../styles/home/homePageStyles'
import { parseCookies } from 'nookies'
import DesktopNavbar from '../components/navbars/desktopNavbar'
import Canvas from '../components/canva/canvas'
import boy1Icon from "../public/images/avatars/boy_avatar1.png"
import { useContext } from 'react'
import { AuthContext } from '../contexts/AuthContext'
import { Actions, Welcome } from '../components/home'
import CreateMatch from "../components/createMatch/createMatch"

const Home: NextPage = () => {
  const [actionActivated, setActionActivated] = useState<string>("")
  const { user } = useContext(AuthContext)

  return (
    <Container isActionActivated={actionActivated.length ? true : false} >
      <Head>
        <title>Drawing app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300&family=Noto+Sans&family=Roboto&family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet" />
      </Head>
      { actionActivated === "createMatch" ? <CreateMatch close={() => setActionActivated("")} /> : null }
      <DesktopNavbar />
      <GeneralContainer>
        <Welcome user={{ name: user.name, pfp: boy1Icon.src }}/>
        <Actions setActionActivated={setActionActivated} />
      </GeneralContainer>
      {/* <Canvas color="yellow" /> */}
    </Container>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { 'drawingauth.token': token } = parseCookies(ctx)

  if (!token) {
    return {
      redirect: {
        destination: "/login",
        permanent: false
      }
    }
  }

  return {
    props: {}
  }
}

export default Home
